from collections.abc import Callable
from enum import Enum
from typing import Any

class Direction(Enum):
    Across = 0
    Down = 1

    def opposite(self) -> Direction: ...

class Symmetry(Enum):
    Rotational = 0
    Full = 1
    Vertical = 2
    Horizontal = 3
    Biaxial = 4
    NeDiagonal = 5
    NwDiagonal = 6

def get_inverse_character_frequencies() -> dict[str, float]: ...

class PyMatchWordList:
    def __init__(
        self, word_length: int, words: list[str], scores: list[float]
    ) -> None: ...
    @property
    def word_length(self) -> int: ...
    @property
    def words(self) -> list[str]: ...
    @property
    def scores(self) -> list[float]: ...
    def letter_scores_at_index(self, index: int) -> dict[str, float]: ...
    def get_score(self, word: str) -> float | None: ...
    def score_filter(self, threshold: float) -> PyMatchWordList: ...
    def filter_words(self, words: list[str]) -> PyMatchWordList: ...
    def rescore(
        self, rescore_fn: Callable[[str, float], float], drop_zeros: bool = True
    ) -> PyMatchWordList: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> tuple[str, float]: ...
    def __contains__(self, word: str) -> bool: ...

class PyWordList:
    def __init__(self, source: str | list[str] | dict[str, float]) -> None: ...
    @staticmethod
    def default() -> PyWordList: ...
    @staticmethod
    def from_words_scores(words: list[str], scores: list[float]) -> PyWordList: ...
    @property
    def words(self) -> list[str]: ...
    @property
    def scores(self) -> list[float]: ...
    def find_matches_str(self, query: str) -> PyMatchWordList: ...
    def score_filter(self, threshold: float) -> PyWordList: ...
    def get_partition(self, length: int) -> tuple[list[str], list[float]] | None: ...
    def fused_cross_matches(
        self,
        word_pattern: str,
        open_positions: list[int],
        letter_weights_per_pos: list[list[float]],
        drop_zeros: bool = True,
    ) -> PyMatchWordList: ...
    def contains(self, word: str) -> bool: ...
    def get_score(self, word: str) -> float | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> tuple[str, float]: ...
    def __contains__(self, word: str) -> bool: ...
    def __add__(self, other: PyWordList) -> PyWordList: ...

class PyCrossword:
    def __init__(
        self,
        num_rows: int | None = None,
        num_cols: int | None = None,
        symmetry: Symmetry | None = None,
        display_size_px: int = 500,
        grid: list[list[str]] | None = None,
    ) -> None: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_cols(self) -> int: ...
    @property
    def display_size_px(self) -> int: ...
    @display_size_px.setter
    def display_size_px(self, val: int) -> None: ...
    @property
    def symmetry(self) -> Symmetry | None: ...
    @symmetry.setter
    def symmetry(self, val: Symmetry | None) -> None: ...
    def get_cell_value(self, row: int, col: int) -> str: ...
    def get_cell_rebus(self, row: int, col: int) -> tuple[str, str] | None: ...
    def set_cell_rebus(self, row: int, col: int, across: str, down: str) -> None: ...
    def get_cell_number(self, row: int, col: int) -> int | None: ...
    def get_cell_across_number(self, row: int, col: int) -> int | None: ...
    def get_cell_down_number(self, row: int, col: int) -> int | None: ...
    def is_cell_black(self, row: int, col: int) -> bool: ...
    def is_cell_empty(self, row: int, col: int) -> bool: ...
    def get_cell_shaded(self, row: int, col: int) -> bool: ...
    def get_cell_circled(self, row: int, col: int) -> bool: ...
    def set_cell_shaded(self, row: int, col: int, val: bool) -> None: ...
    def set_cell_circled(self, row: int, col: int, val: bool) -> None: ...
    def set_cell_value(self, row: int, col: int, value: str) -> None: ...
    def set_word_value(self, direction: Direction, number: int, value: str) -> None: ...
    def get_word_value(self, direction: Direction, number: int) -> str | None: ...
    def is_word_open(self, direction: Direction, number: int) -> bool: ...
    def get_word_length(self, direction: Direction, number: int) -> int | None: ...
    def get_word_cell_indices(
        self, direction: Direction, number: int
    ) -> list[tuple[int, int]] | None: ...
    def get_word_crosses(
        self, direction: Direction, number: int
    ) -> list[tuple[Direction, int] | None] | None: ...
    def get_word_at_cell(
        self, row: int, col: int, direction: Direction
    ) -> tuple[Direction, int] | None: ...
    def get_symmetric_cell_indices(
        self, row: int, col: int
    ) -> list[tuple[int, int]]: ...
    def get_symmetric_word_indices(
        self, direction: Direction, number: int
    ) -> list[tuple[Direction, int]]: ...
    def get_clue(self, direction: Direction, number: int) -> str: ...
    def set_clue(self, direction: Direction, number: int, clue: str) -> None: ...
    def get_clues(self) -> list[tuple[tuple[Direction, int], str]]: ...
    def get_open_subgrids(self) -> list[list[tuple[Direction, int]]]: ...
    def get_disconnected_open_subgrids(self) -> list[list[tuple[Direction, int]]]: ...
    def numbers_grid(self) -> list[list[int]]: ...
    def across_numbers_grid(self) -> list[list[int]]: ...
    def down_numbers_grid(self) -> list[list[int]]: ...
    def iter_word_indices(
        self, direction: Direction | None = None, only_open: bool = False
    ) -> list[tuple[Direction, int]]: ...
    def compute_subgraph_hash(self, subgraph: list[tuple[Direction, int]]) -> int: ...
    def fill(
        self,
        word_list: PyWordList,
        timeout_secs: float | None = None,
        timeout: float | None = None,
        temperature: float = 0.0,
        score_filter: float | None = None,
        allow_repeats: bool = False,
        upweight_diverse_letters: bool = False,
    ) -> PyCrossword | None: ...
    def check(
        self,
        symmetry: Symmetry | None = None,
        min_word_length: int = 3,
        allow_duplicates: bool = False,
        require_connected: bool = True,
        require_filled: bool = False,
    ) -> tuple[bool, list[str], list[str]]: ...
    def stats(self) -> dict[str, Any]: ...
    def copy(self) -> PyCrossword: ...
